name: puxbay
description: Official Dart/Flutter SDK for the Puxbay POS API - Production-ready client library
version: 1.0.0
homepage: https://github.com/puxbay/puxbay-dart
repository: https://github.com/puxbay/puxbay-dart
issue_tracker: https://github.com/puxbay/puxbay-dart/issues
documentation: https://docs.puxbay.com

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  http: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.0
  mockito: ^5.4.2
  lints: ^2.1.0

topics:
  - api
  - pos
  - retail
  - sdk
