name: .NET SDK

on:
  push:
    paths:
      - 'sdks/dotnet/**'
  pull_request:
    paths:
      - 'sdks/dotnet/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd sdks/dotnet
        dotnet restore
    - name: Build
      run: |
        cd sdks/dotnet
        dotnet build --no-restore
    - name: Test
      run: |
        cd sdks/dotnet
        dotnet test --no-build --verbosity normal
